// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Author: typeof import('./../components/Layout/SideBar/Author.vue')['default']
    BlogInfo: typeof import('./../components/Layout/SideBar/BlogInfo.vue')['default']
    Catalog: typeof import('./../components/Catalog/index.vue')['default']
    Drawer: typeof import('./../components/Layout/Drawer/index.vue')['default']
    Echarts: typeof import('./../components/Echarts/index.vue')['default']
    Footer: typeof import('./../components/Layout/Footer/index.vue')['default']
    Header: typeof import('./../components/Layout/Header/index.vue')['default']
    NavBar: typeof import('./../components/Layout/Header/NavBar.vue')['default']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Notice: typeof import('./../components/Layout/SideBar/Notice.vue')['default']
    NPagination: typeof import('naive-ui')['NPagination']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    Paging: typeof import('./../components/Pagination/Paging.vue')['default']
    Provider: typeof import('./../components/Provider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Dialog/Search.vue')['default']
    SideBar: typeof import('./../components/Layout/SideBar/index.vue')['default']
    SocialList: typeof import('./../components/Layout/SideBar/SocialList.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Toggle: typeof import('./../components/Layout/Header/Toggle.vue')['default']
    Tool: typeof import('./../components/Tool/index.vue')['default']
    Waves: typeof import('./../components/Waves/index.vue')['default']
    WebInfo: typeof import('./../components/Layout/SideBar/WebInfo.vue')['default']
  }
}
